# -*- coding: utf-8 -*-
"""functions_arrays_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhn5EAnWUmYfO9L8la67RpwDCMH-dfF6
"""

# 1. Array Sum
#Write a function that accepts a list of numbers and returns the sum of all elements.

# Given List
numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

# 1. Array Sum
# Function to calculate sum of all elements

def find_sum(arr):
    total = 0
    for num in arr:
        total += num
    return total

print("Sum of elements:", find_sum(numbers))

#2. Maximum Element
#Write a function to find the largest element in a list without using max().

# Given List
numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

# 2. Maximum Element
# Function to find largest element without using max()

def find_maximum(arr):
    largest = arr[0]

    for num in arr:
        if num > largest:
            largest = num

    return largest

print("Largest element:", find_maximum(numbers))

# 3. Even Numbers Counter
#Write a function that counts how many even numbers are present in a list.

# Given List
numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

# 3. Even Numbers Counter
# Function to count even numbers

def count_even_numbers(arr):
    count = 0

    for num in arr:
        if num % 2 == 0:
            count += 1

    return count

print("Even numbers count:", count_even_numbers(numbers))

# 4. Reverse Array
#Write a function to reverse the elements of a list.

# Given List
numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

# 4. Reverse Array
# Function to reverse list elements

def reverse_array(arr):
    reversed_list = arr[::-1]
    return reversed_list

print("Reversed list:", reverse_array(numbers))

#5. Search Element
#Write a function to search for a given element in a list and return its index.

# Given List
numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

# 5. Search Element
# Function to search element and return index

def search_element(arr, element):
    for index in range(len(arr)):
        if arr[index] == element:
            return index

    return -1

search_num = 56

result = search_element(numbers, search_num)

if result != -1:
    print("Element found at index:", result)
else:
    print("Element not found")

#6 Palindrome List
#Write a function to check whether a list reads the same forward and backward.

def check_palindrome(arr):
    if arr == arr[::-1]:
        return True
    else:
        return False

list1 = [1, 2, 3, 2, 1]

if check_palindrome(list1):
    print("List is palindrome")
else:
    print("List is not palindrome")

#7 Second Largest Number
#Write a function to find the second largest number in a list.

numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]
def second_largest(arr):
    largest = second = -1

    for num in arr:
        if num > largest:
            second = largest
            largest = num
        elif num > second and num != largest:
            second = num

    return second

print("Second largest number:", second_largest(numbers))

#8
#
numbers = [45, 12, 78, 34, 78, 90, 12, 56, 23, 45]

# 8. Duplicate Elements
# Function to identify duplicate elements

def find_duplicates(arr):
    duplicates = []

    for num in arr:
        if arr.count(num) > 1 and num not in duplicates:
            duplicates.append(num)

    return duplicates

print("Duplicate elements:", find_duplicates(numbers))

# 9. Function for Student Marks
# Function to find average, highest and lowest marks

student_marks = [85, 72, 90, 67, 95, 88]

def analyze_marks(marks):
    total = 0

    for mark in marks:
        total += mark

    average = total / len(marks)

    highest = marks[0]
    lowest = marks[0]

    for mark in marks:
        if mark > highest:
            highest = mark

        if mark < lowest:
            lowest = mark

    return average, highest, lowest

avg, high, low = analyze_marks(student_marks)

print("Average Marks:", avg)
print("Highest Marks:", high)
print("Lowest Marks:", low)